name: Scala

on:
  pull_request: {}
  push:
    branches:
      - series/1.x # CE3
    paths:
      - "modules/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Starting up Valkey 🐳"
        run: docker compose up -d

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v6

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v27

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: redis4cats
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Run tests and compile documentation 🚀"
        run: nix develop -c sbt 'buildRedis4Cats'

      - name: "Test for Binary Compatibility 📦"
        run: nix develop -c sbt 'mimaReportBinaryIssuesIfRelevant'

      - name: "Shutting down Valkey 🐳"
        run: docker compose down
